sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
<<<<<<< HEAD
    password: 123456
=======
    password: root
>>>>>>> 5e5b6e5ae2c7ab2773bfa65a5341987e7d8934ae
